name: DEV. Build

on:
  push:
    branches:
      - "dev"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        required: false
        description: "Test scenario tags"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 18.18.2
        uses: actions/setup-node@v1
        with:
          node-version: "18.18.2"
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: knois/tasks-web/dev
          registry: docker.pkg.github.com
          username: Knois
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest
  trigger_to_deploy_docker_img:
    name: Dispatch to `init-repo`
    runs-on: ubuntu-latest
    needs: build
    steps:
      # - name: Emit repository_dispatch
      #   uses: mvasigh/dispatch-action@main
      #   with:
      #     token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     repo: init-repo
      #     owner: l423r
      #     event_type: dev-tasks-web-deploy
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: l423r/init-repo
          event-type: dev-tasks-web-deploy
          client-payload: '{"message": "${{ github.event.commits[0].message }}", "sha": "${{ github.sha }}"}'
  finish:
    needs: trigger_to_deploy_docker_img
    name: Send notification for finish
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on finish workflows
        uses: appleboy/telegram-action@master
        with:
          to: ${{ vars.TELEGRAM_TO }}
          token: ${{ vars.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

            CI completed,  message sent to start CD
